formfield_index:
    path:     /
    defaults: { _controller: "AppBundle:FormField:index" }
    methods:  GET

formfield_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:FormField:show" }
    methods:  GET

formfield_new:
    path:     /new
    defaults: { _controller: "AppBundle:FormField:new" }
    methods:  [GET, POST]

formfield_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:FormField:edit" }
    methods:  [GET, POST]

formfield_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:FormField:delete" }
    methods:  DELETE
